"""adiciona diario_alunos e campos professor

Revision ID: 16f242611856
Revises: c2d3e4f5a6b7
Create Date: 2026-05-07 16:46:51.993554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f242611856'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diario_alunos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sa.String(length=200), nullable=False),
    sa.Column('aluno_matricula', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disciplina_id', 'aluno_id', name='uq_diario_aluno')
    )
    op.add_column('alunos', sa.Column('matricula', sa.String(length=50), nullable=True))
    op.add_column('alunos', sa.Column('suap_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'alunos', ['suap_id'])
    op.create_unique_constraint(None, 'alunos', ['matricula'])
    op.add_column('disciplinas', sa.Column('diario_id', sa.Integer(), nullable=True))
    op.add_column('disciplinas', sa.Column('codigo_turma', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disciplinas', 'codigo_turma')
    op.drop_column('disciplinas', 'diario_id')
    op.drop_constraint(None, 'alunos', type_='unique')
    op.drop_constraint(None, 'alunos', type_='unique')
    op.drop_column('alunos', 'suap_id')
    op.drop_column('alunos', 'matricula')
    op.drop_table('diario_alunos')
    # ### end Alembic commands ###
