"""Add aluno_id foreign key to perfis_aluno

Revision ID: 6f2c5e53a895
Revises: bcefcf45b50b
Create Date: 2026-04-29 08:22:20.255325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2c5e53a895'
down_revision: Union[str, None] = 'bcefcf45b50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
