"""add_acomodacao_observacoes

Revision ID: 746c64112447
Revises: 91710d0a9f13
Create Date: 2026-06-17 10:07:01.234098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746c64112447'
down_revision: Union[str, None] = '91710d0a9f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acomodacao_observacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'disciplina_id', 'professor_id', name='uq_acomodacao_obs')
    )
#    op.drop_index('ix_alunos_status_acompanhamento', table_name='alunos')
#    op.drop_index('ix_conversas_usuario_id', table_name='conversas')
#    op.drop_index('ix_diario_alunos_aluno_id', table_name='diario_alunos')
#    op.drop_index('ix_diario_alunos_disciplina_id', table_name='diario_alunos')
    op.drop_index('ix_disciplinas_usuario_id', table_name='disciplinas')
    op.drop_index('ix_pendencias_validacao_aluno_id', table_name='pendencias_validacao')
    op.drop_index('ix_pendencias_validacao_status', table_name='pendencias_validacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pendencias_validacao_status', 'pendencias_validacao', ['status'], unique=False)
    op.create_index('ix_pendencias_validacao_aluno_id', 'pendencias_validacao', ['aluno_id'], unique=False)
    op.create_index('ix_disciplinas_usuario_id', 'disciplinas', ['usuario_id'], unique=False)
    op.create_index('ix_diario_alunos_disciplina_id', 'diario_alunos', ['disciplina_id'], unique=False)
    op.create_index('ix_diario_alunos_aluno_id', 'diario_alunos', ['aluno_id'], unique=False)
    op.create_index('ix_conversas_usuario_id', 'conversas', ['usuario_id'], unique=False)
    op.create_index('ix_alunos_status_acompanhamento', 'alunos', ['status_acompanhamento'], unique=False)
    op.drop_table('acomodacao_observacoes')
    # ### end Alembic commands ###
