"""Add aluno_id foreign key to perfis_aluno

Revision ID: bcefcf45b50b
Revises: 3db0489a54a6
Create Date: 2026-04-28 21:45:27.697666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcefcf45b50b'
down_revision: Union[str, None] = '3db0489a54a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conteudos_gerados_aluno_id', table_name='conteudos_gerados')
    op.drop_index('ix_conteudos_gerados_usuario_id', table_name='conteudos_gerados')
    op.drop_index('ix_perfis_aluno_aluno_id', table_name='perfis_aluno')
    op.create_unique_constraint(None, 'perfis_aluno', ['aluno_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfis_aluno', type_='unique')
    op.create_index('ix_perfis_aluno_aluno_id', 'perfis_aluno', ['aluno_id'], unique=False)
    op.create_index('ix_conteudos_gerados_usuario_id', 'conteudos_gerados', ['usuario_id'], unique=False)
    op.create_index('ix_conteudos_gerados_aluno_id', 'conteudos_gerados', ['aluno_id'], unique=False)
    # ### end Alembic commands ###
