"""add_acomodacao_audit_material_notificacao_tokenrevogado_feedback

Revision ID: c299aa25e88e
Revises: b5dd2dfa4a6d
Create Date: 2026-08-27 09:34:50.848802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c299aa25e88e'
down_revision: Union[str, None] = 'b5dd2dfa4a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteudo_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao', sa.String(length=12), nullable=False),
    sa.Column('utilidade_percebida', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=1000), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos_gerados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conteudo_id', 'professor_id', 'disciplina_id', name='uq_conteudo_feedback')
    )
    op.create_index('ix_conteudo_feedback_conteudo_id', 'conteudo_feedback', ['conteudo_id'], unique=False)
    op.create_index('ix_conteudo_feedback_professor_id', 'conteudo_feedback', ['professor_id'], unique=False)

    # --- Manual additions for tables that already exist in local DB ---

    # acomodacao_observacoes
    op.create_table('acomodacao_observacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'disciplina_id', 'professor_id', name='uq_acomodacao_obs')
    )

    # audit_logs
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=30), nullable=False),
    sa.Column('recurso_tipo', sa.String(length=50), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_aluno_id', 'audit_logs', ['aluno_id'], unique=False)
    op.create_index('ix_audit_logs_recurso', 'audit_logs', ['recurso_tipo', 'recurso_id'], unique=False)
    op.create_index('ix_audit_logs_usuario', 'audit_logs', ['usuario_id'], unique=False)
    op.create_index('ix_audit_logs_criado_em', 'audit_logs', ['criado_em'], unique=False)

    # materiais
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=300), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=100), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=50), nullable=False),
    sa.Column('tamanho', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), server_default='outro', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_arquivo')
    )
    op.create_index(op.f('ix_materiais_disciplina_id'), 'materiais', ['disciplina_id'], unique=False)

    # notificacoes
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('destino_tipo', sa.String(length=50), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    # notificacao_leitura
    op.create_table('notificacao_leitura',
    sa.Column('notificacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('lida_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('excluida', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacao_id', 'usuario_id')
    )

    # tokens_revogados
    op.create_table('tokens_revogados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_tokens_revogados_jti'), 'tokens_revogados', ['jti'], unique=True)
    op.create_index(op.f('ix_tokens_revogados_usuario_id'), 'tokens_revogados', ['usuario_id'], unique=False)

    op.drop_index('ix_conversas_atualizada_em', table_name='conversas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversas_atualizada_em', 'conversas', ['atualizada_em'], unique=False)

    # --- Manual drops (reverse order of creation) ---
    op.drop_index(op.f('ix_tokens_revogados_usuario_id'), table_name='tokens_revogados')
    op.drop_index(op.f('ix_tokens_revogados_jti'), table_name='tokens_revogados')
    op.drop_table('tokens_revogados')

    op.drop_table('notificacao_leitura')
    op.drop_table('notificacoes')

    op.drop_index(op.f('ix_materiais_disciplina_id'), table_name='materiais')
    op.drop_table('materiais')

    op.drop_index('ix_audit_logs_criado_em', table_name='audit_logs')
    op.drop_index('ix_audit_logs_usuario', table_name='audit_logs')
    op.drop_index('ix_audit_logs_recurso', table_name='audit_logs')
    op.drop_index('ix_audit_logs_aluno_id', table_name='audit_logs')
    op.drop_table('audit_logs')

    op.drop_table('acomodacao_observacoes')

    op.drop_index('ix_conteudo_feedback_professor_id', table_name='conteudo_feedback')
    op.drop_index('ix_conteudo_feedback_conteudo_id', table_name='conteudo_feedback')
    op.drop_table('conteudo_feedback')
    # ### end Alembic commands ###
