"""add notificacoes table

Revision ID: fae763a825b7
Revises: 765d5d591f72
Create Date: 2026-06-09 10:17:48.306654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae763a825b7'
down_revision: Union[str, None] = '765d5d591f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('destino_tipo', sa.String(length=50), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
