"""add_tokens_revogados_table

Revision ID: ff83d0426b0e
Revises: i3j4k5l6m7n8
Create Date: 2026-07-21 08:54:13.207135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff83d0426b0e'
down_revision: Union[str, None] = 'i3j4k5l6m7n8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_revogados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_revogados_jti'), 'tokens_revogados', ['jti'], unique=True)
    op.create_index(op.f('ix_tokens_revogados_usuario_id'), 'tokens_revogados', ['usuario_id'], unique=False)
    op.drop_index('ix_conteudo_feedback_conteudo_id', table_name='conteudo_feedback')
    op.drop_index('ix_conteudo_feedback_professor_id', table_name='conteudo_feedback')
    op.drop_table('conteudo_feedback')
    op.drop_index('ix_alunos_campus', table_name='alunos')
    op.drop_index('ix_alunos_status_acompanhamento', table_name='alunos')
    op.add_column('contas_locais', sa.Column('tentativas_login', sa.Integer(), server_default='0', nullable=False))
    op.add_column('contas_locais', sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))
    op.drop_column('notificacoes', 'lida')
    op.drop_index('ix_conteudos_gerados_aluno_id', table_name='conteudos_gerados')
    op.drop_index('ix_conteudos_gerados_conteudo_pai_id', table_name='conteudos_gerados')
    op.drop_index('ix_conversas_usuario_id', table_name='conversas')
    op.drop_index('ix_diario_alunos_aluno_id', table_name='diario_alunos')
    op.drop_index('ix_diario_alunos_disciplina_id', table_name='diario_alunos')
    op.drop_index('ix_disciplinas_semestre', table_name='disciplinas')
    op.drop_index('ix_materiais_categoria', table_name='materiais')
    op.drop_index('ix_notificacoes_criada_em', table_name='notificacoes')
    op.drop_index('ix_notificacoes_destino', table_name='notificacoes')
    op.drop_index('ix_usuarios_campus', table_name='usuarios')
    op.drop_index('ix_usuarios_tipo_perfil', table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuarios_tipo_perfil', 'usuarios', ['tipo_perfil'], unique=False)
    op.create_index('ix_usuarios_campus', 'usuarios', ['campus'], unique=False)
    op.create_index('ix_notificacoes_destino', 'notificacoes', ['destino_tipo', 'destino_id'], unique=False)
    op.create_index('ix_notificacoes_criada_em', 'notificacoes', ['criada_em'], unique=False)
    op.create_index('ix_materiais_categoria', 'materiais', ['categoria'], unique=False)
    op.create_index('ix_disciplinas_semestre', 'disciplinas', ['semestre'], unique=False)
    op.create_index('ix_diario_alunos_disciplina_id', 'diario_alunos', ['disciplina_id'], unique=False)
    op.create_index('ix_diario_alunos_aluno_id', 'diario_alunos', ['aluno_id'], unique=False)
    op.create_index('ix_conversas_usuario_id', 'conversas', ['usuario_id'], unique=False)
    op.create_index('ix_conteudos_gerados_conteudo_pai_id', 'conteudos_gerados', ['conteudo_pai_id'], unique=False)
    op.create_index('ix_conteudos_gerados_aluno_id', 'conteudos_gerados', ['aluno_id'], unique=False)
    op.add_column('notificacoes', sa.Column('lida', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('contas_locais', 'bloqueado_ate')
    op.drop_column('contas_locais', 'tentativas_login')
    op.create_index('ix_alunos_status_acompanhamento', 'alunos', ['status_acompanhamento'], unique=False)
    op.create_index('ix_alunos_campus', 'alunos', ['campus'], unique=False)
    op.create_table('conteudo_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conteudo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disciplina_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avaliacao', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('comentario', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('utilidade_percebida', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudos_gerados.id'], name='conteudo_feedback_conteudo_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], name='conteudo_feedback_disciplina_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], name='conteudo_feedback_professor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='conteudo_feedback_pkey'),
    sa.UniqueConstraint('conteudo_id', 'professor_id', 'disciplina_id', name='uq_conteudo_feedback')
    )
    op.create_index('ix_conteudo_feedback_professor_id', 'conteudo_feedback', ['professor_id'], unique=False)
    op.create_index('ix_conteudo_feedback_conteudo_id', 'conteudo_feedback', ['conteudo_id'], unique=False)
    op.drop_index(op.f('ix_tokens_revogados_usuario_id'), table_name='tokens_revogados')
    op.drop_index(op.f('ix_tokens_revogados_jti'), table_name='tokens_revogados')
    op.drop_table('tokens_revogados')
    # ### end Alembic commands ###
